@startuml
 class UserController {
 	userService:UserService
 	uploadPath:String
 	UserController()
 	cabinet()
 	getUserUpdatePage()
 	String updateUser()
 	List<String> updateUser()
 	updateFilePath()
 	register()
 	addUser()
 }
@enduml