version: "3"

services:
  postgres:
    image: postgres:11-alpine
    restart: always
    ports:
      - "127.0.0.1:8432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: sweater
    volumes:
      - /home/spotyk/Desktop/diplom/springApp/docker/script/:/docker-entrypoint-initdb.d
      ##docker-compose up
