@startuml
 class OrderController {
     orderService:OrderService
     OrderDetailsService orderDetailsService;
     OrderController()
     getOrderPage()
     getOrderDetailsByOrderId()
  	 adminChangeOrderStatus()
}
@enduml