@startuml
class OrderDetails {
	id:Long
	order:Order
	product:ProductEntity
	Long quantity:
	getId()
	setId()
	getOrder()
	voidsetOrder()
	getProduct()
	setProduct()
	getQuantity()
	setQuantity()
}
@enduml